### PR TITLE
Code style for JetBrains IDEs.

### PR DESCRIPTION
**Pull request by richseviora**
Configures project code style for other JetBrains IDE users.

### CODE REVIEW

**Comment by mxxcon** [comment]
Perhaps also use http://editorconfig.org as a more universal choice for code style?

**Comment by richseviora** [comment]
@mxxcon done!

**Comment by mxxcon** [comment]
Also in relation to this, perhaps if you are dealing with JetBrains IDEs, perhaps include (some?) of the stuff from https://www.gitignore.io/api/jetbrains?

**Comment by richseviora** [comment]
@mxxcon Also done! Thanks for the suggestion :) Commits have been squashed.

**Pull request merged**
