### PR TITLE
Update IITC_WebViewClient.java & AndroidManifest.xml to support new intel url on 10/29/18

### PR DESCRIPTION
**Pull request by EvoldicA**
Adds new URL for intel change on 10/29/18.

### CODE REVIEW

**Comment by terencehonles** [comment]
#1277 does the same with wildcards in case they change it again

**Comment by EvoldicA** [comment]
> #1277 does the same with wildcards in case they change it again

I thought about using wildcards as you did.  I went with hardcoded urls to err on the side of safety, and fall in line with the previous code style.  Not sure if anyone is maintaining this anymore as it's been ages since the last commit.

**Comment by fkloft** [comment]
Please don't forget the mission permalinks.

**Comment by McBen** [comment]
same as in #1277 -> "https://intel.ingress.com/*" is the valid url-path.

**Comment by EvoldicA** [comment]
Thanks for the comments.  Now it should be better.  I'm cutting myself off until I get more sleep, and get my test environment set up proper.

**Comment by adnans** [comment]
> Thanks for the comments. Now it should be better. I'm cutting myself off until I get more sleep, and get my test environment set up proper.

using /intel needs to be put to an end at this point.

**Pull request closed without merging**
