### PR TITLE
Add an ownership plugin to enable users to track their own guardians

### PR DESCRIPTION
**Pull request by michaeldever**
screen shot 2015-04-10 at 20 10 14

This plugin keeps track of portals that are currently owned by the user, to allow a user to track their guardians, persisted via sync.
- Attempts to automatically identify owned/neutralised portals based on COMM
- Allows for manual identification of owned portals
- Injects ownership information into the portals list plugin
  - Uniques plugin modified as a result, in order to keep the ownership & unique information together
- Also creates a dialog like portals-list which shows all currently known portals owned by the user
  - This is based on the previously known information, which can be updated by viewing each of the owned portals again.
  - Dialog shows portals both inside and outside of the bounds of the screen, with smart link generation.
    - If the user selects a portal within the bounds of the screen, its details are shown and ownership information updated.
    - If the user selects a portal outside the bounds of the screen, the screen is repositioned to the portals co-ordinates and its details are shown and ownership information updated.
  - The portal information for every portal can be updated automatically by clicking 'Refresh All'.
    - This required a modification to dialogs to allow for user defined buttons, and a resulting css change.
    - This attempts to be smart in loading to limit requests to NIA:
      - If the portal is within the bounds of the map it simply renders its update, removing a map-request.
      - If the portal is outside the bounds of the map it zooms to the portal and renders.
- As NIA don't provide information on capture dates for portals, the capture date is initially set to be when the capture is recorded by the plugin (i.e. now), however the dialog of owned portals allows for this to be manually updated if the user double clicks on the number of days the portal is owned.

Screenshot attached, portal names modified, obviously.

### CODE REVIEW

**Comment by michaeldever** [comment]
Any word on this? A few friends are using it currently and find it quite useful.

**Comment by ruharen** [comment]
I like this :)

**Comment by belko-letyago** [comment]
Very useful plugin!

**Comment by michaeldever** [comment]
@belko-letyago thanks. It would be nice to see it pulled in!

**Comment by michaeldever** [comment]
@jonatkins Any chance of getting this pulled, quite a few people are finding it useful now.

**Comment by maztoyz** [comment]
how to use this plugin..??

**Comment by brianjking** [comment]
@michaeldever Since this hasn't been merged in yet can you provide some tips on how to add this to my existing IITC install using Tampermonkey/Chrome?

Thanks!

**Comment by ranescarter** [comment]
@michaeldever Add me to the list of those interested in getting this installed. Sounds like a great plugin.

**Comment by McBen** [comment]
how to build - the dirty way:
-> install phyton
-> download & extract michaeldever source -> https://github.com/michaeldever/ingress-intel-total-conversion
-> run build-script -> "./build.py local"

stuff will be at "./build/local/plugins/portal-ownership.user.js"

Notes:
- AFAIK chrome will block direct script installs: create a new TM script and copy&paste the content from the plugin script file
- don't use the other generated script files 'cause they are out-of-date (that why I call it dirty)
- you'll miss the "refresh all" button 'cause it requires the iitc (main) update
- the 'uniques' plugin was modified too..not sure if it's required

**Comment by ranescarter** [comment]
I have been using this plug-in for a week or so.  I have it installed on my laptop and mobile.  It has synced well and it pretty useful.  I think it would be a great addition to the plug-ins offered by IITC.  

Thanks to @michaeldever for the hard work.

**Comment by yoshimo** [comment]
very nice idea, was looking for something like this.
@michaeldever  would it be possible to add an expert setting to optionally slowly poll older chathistory to find the capture date? I don't remember all of my portal trips and it would be good to have the dates before the counter for the guardian medal increases again (which is inaccurate in itself as well).

**Comment by PrinterElf** [comment]
Ok, so this has gone from in essence a glorified version of the Uniques plugin, to what is currently already automating data collection, and now being proposed as a full on comm scraper.

While the suggestion of inclusion a year ago might possibly have been one which could have been debated with a few tweaks, I think you're now well beyond the grey area in which IITC operates and in completely in the wrong place for this plugin.

**Comment by michaeldever** [comment]
@yoshimo no, there isn't a way that would be done. That would very much breach T&C, as well as not being the purpose of this plugin. @PrinterElf that was not my proposal, and tbh, this only allows you to keep track of your own data. It can't be used for tracking other peoples guardians etc.

TBH, I'd forgotten about this after sitting here for a year and a half in limbo.

**Comment by abdulhaleembaram** [comment]
I like

**Comment by myapps021** [comment]
How do i use this? I downloaded python and i dont know the next step to do @McBen Thanks

**Comment by myapps021** [comment]
@ranescarter hi can you teach me how to use this?

**Comment by myapps021** [comment]
@michaeldever hi how do I use this?

**Comment by AngelDesire** [comment]
Sir,im newbie here. how to install that plugin to my iitc?
Thanks

**Comment by s-chizhik** [comment]
@AngelDesire clone this repo to your pc, apply this patch, run `./build.py local` and install script from build directory.

**Comment by AngelDesire** [comment]
I really not understand about build.py local.
how to clone and apply to my iitc.
i really like to learn something new like this.
Can someone teach me?

**Comment by lostsnow** [comment]
good work! thx.

**Comment by AlgarMaks** [comment]
I am really sorry, but I read post with installation instructions from  11 Jan 2016 and I could not run it. Looks like I missed something.
Could anyone write instructions step by step please?

**Comment by McBen** [comment]
nothing changed.  make sure you run "build.py local"

http://superuser.com/questions/747684/how-can-i-run-an-application-with-arguments-from-windows-explorer

**Comment by Teamtyler2** [comment]
does this still work?

**Comment by ranescarter** [comment]
@Teamtyler2 ~ I still use the Ownership plugin.  I moved "Health" and "Days Owned" to be right after "Portal Name" to make it easier on my mobile.

**Comment by Teamtyler2** [comment]
@ranescarter How did u get it to run on your phone?

**Comment by ranescarter** [comment]
I emailed the portal-ownership.user.js to myself.  Opening the file on my mobile initiated the app and self installed.

**Comment by Teamtyler2** [comment]
@ranescarter can u explain how i can get the portal-ownership.user.js script i want to get it on my phone and my pc but idk how to get the portal-ownership.user.js

**Comment by ranescarter** [comment]
It was a learning process for me.  Trial and error.  

Using the link provided by McBen about this time last year (Thanks McBen):
https://github.com/michaeldever/ingress-intel-total-conversion/archive/master.zip

I downloaded that zip file and copied the .js file to my PC
ingress-intel-total-conversion-master > plugins > portal-ownership.user.js

On my PC, I opened Tampermonkey, opened the Utilities tab, and pasted the URL of the file location on my PC.  (C:\....\desktop in my case).   Another option, if you know how, is to copy the code from the .js file and use the <new userscript> option in Tampermonkey.  I didn't realize that the first few times I attempted to install.  

With the help of someone who knows a lot more about coding than I do, I updated the file in Tampermonkey and exported that file.  I emailed that file to myself so I can install it on my mobile, home PC, etc.   

Sure hope that helps.  Is about all I can remember.

**Comment by Teamtyler2** [comment]
@ranescarter do i need to disable the rest of my plugins?

**Comment by ranescarter** [comment]
I didn't have to.  I have about 25 plugins installed.  Most are enabled.

**Comment by Teamtyler2** [comment]
@ranescarter Trying Right Now

**Comment by Teamtyler2** [comment]
@ranescarter Im getting cant run script from url when i use the url

**Comment by Teamtyler2** [comment]
@ranescarter could u email me the script

**Comment by ranescarter** [comment]
Sorry Tyler.  That is the process that worked for me.  I am certain there are other methods... probably even better methods, but that is what worked for me.  

The file is in the zip file.  
https://github.com/michaeldever/ingress-intel-total-conversion/archive/master.zip
ingress-intel-total-conversion-master > plugins > portal-ownership.user.js

**Comment by Teamtyler2** [comment]
@ranescarter i did what u said to do in your last message idk what i did wrong hm

**Comment by smaynard** [comment]
Ok, have the script installed, where is the ownership info displayed?

**Comment by TexasResistance** [comment]
I installed successfully via Tampermonkey by copying the script, and it shows to be installed and running. The owned portals now show up in red, but I can't find where to pull up the dialog of portals owned (like the one on your screenshot above). How do you get to the dialog screen or the list of portals owned screen?

**Comment by Fofao** [comment]
Very good work. I´m using it and is very practical...

**Comment by Fofao** [comment]
TexasResistance, you need to compile the code, like McBen explained...

**Comment by KeyonPT** [comment]
this still work? i cant instal it anyaway, getting error all the time :(

**Pull request closed without merging**
